/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhodt;

/**
 *
 * @author kax20
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QLUserbtn = new javax.swing.JButton();
        QLXuatNhapKhobtn = new javax.swing.JButton();
        QLKhobtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QLUserbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        QLUserbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/User-Manager-icon.png"))); // NOI18N
        QLUserbtn.setText("Quản Lý User");
        QLUserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLUserbtnActionPerformed(evt);
            }
        });

        QLXuatNhapKhobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        QLXuatNhapKhobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/HandTruck-2-icon.png"))); // NOI18N
        QLXuatNhapKhobtn.setText("Quản Lý Xuất Nhập Kho");
        QLXuatNhapKhobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLXuatNhapKhobtnActionPerformed(evt);
            }
        });

        QLKhobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        QLKhobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/Warehouse-icon.png"))); // NOI18N
        QLKhobtn.setText("Quản Lý Kho");
        QLKhobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKhobtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setText("MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QLUserbtn)
                        .addGap(30, 30, 30)
                        .addComponent(QLXuatNhapKhobtn)
                        .addGap(35, 35, 35)
                        .addComponent(QLKhobtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLUserbtn)
                    .addComponent(QLXuatNhapKhobtn)
                    .addComponent(QLKhobtn))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLXuatNhapKhobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLXuatNhapKhobtnActionPerformed
        // TODO add your handling code here:
        QuanLyXuatNhap a = new QuanLyXuatNhap();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_QLXuatNhapKhobtnActionPerformed

    private void QLUserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLUserbtnActionPerformed
        // TODO add your handling code here:
        QuanLyUser a = new QuanLyUser();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_QLUserbtnActionPerformed

    private void QLKhobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKhobtnActionPerformed
        // TODO add your handling code here:
        QuanLyKho a = new QuanLyKho();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_QLKhobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QLKhobtn;
    private javax.swing.JButton QLUserbtn;
    private javax.swing.JButton QLXuatNhapKhobtn;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
