/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhodt;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kax20
 */
public class NhapKho extends javax.swing.JFrame {

     DefaultTableModel tableModel;
    List<DienThoai> DienThoailist = new ArrayList<>();
    int selectedP = -1;
    /**
     * Creates new form NhapKho
     */
    public NhapKho() {
        initComponents();
        tableModel = (DefaultTableModel) Khotbl.getModel();
        showDienThoai();
        Khotbl.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                selectedP = Khotbl.getSelectedRow();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Matxt = new javax.swing.JTextField();
        HDHtxt = new javax.swing.JTextField();
        SoLuongtxt = new javax.swing.JTextField();
        Mautxt = new javax.swing.JTextField();
        Tentxt = new javax.swing.JTextField();
        Ngaytxt = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Khotbl = new javax.swing.JTable();
        Nhapbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã Điện Thoại");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên Điện Thoại");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Hệ Điều Hành");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số Lượng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Màu");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày");

        Khotbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Điện Thoại", "Tên Điện Thoại", "Hệ Điều Hành", "Màu", "Số Lượng", "Ngày"
            }
        ));
        Khotbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhotblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Khotbl);

        Nhapbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nhapbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/Add-Property-icon.png"))); // NOI18N
        Nhapbtn.setText("Nhập");
        Nhapbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapbtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setText("NHẬP KHO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nhapbtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SoLuongtxt)
                                .addComponent(Ngaytxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(Matxt)
                                .addComponent(Tentxt)
                                .addComponent(HDHtxt)
                                .addComponent(Mautxt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel9)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Matxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HDHtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mautxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SoLuongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Ngaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Nhapbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhapbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapbtnActionPerformed
        // TODO add your handling code here:
        String ma = Matxt.getText();
        String ten = Tentxt.getText();
        String hdh = HDHtxt.getText();
        String mau = Mautxt.getText();
        int soluong = Integer.parseInt(SoLuongtxt.getText());
        Date ngay = Ngaytxt.getDate();
        DienThoai dtn = new DienThoai(ma, ten, hdh, mau, soluong, ngay);
        DienThoailist.forEach(dienthoai -> {
            if(dienthoai.getMaDT().equals(dtn.getMaDT()) && dienthoai.getTenDT().equals(dtn.getTenDT()) && dienthoai.getHDH().equals(dtn.getHDH()) && dienthoai.getMauDT().equals(dtn.getMauDT())){
                Phieu a = new Phieu(ma, ten, hdh, mau, soluong, ngay);
                NhapPhieu(a);
                dtn.setSoLuong(soluong + dienthoai.getSoLuong());
                DienThoaimodify.update(dtn);
                showDienThoai();
                Matxt.setText("");
                HDHtxt.setText("");
                Tentxt.setText("");
                Mautxt.setText("");
                SoLuongtxt.setText("");
            }
        });
        if(!Matxt.getText().equals("")){
            Phieu a = new Phieu(ma, ten, hdh, mau, soluong, ngay);
            NhapPhieu(a);
            DienThoaimodify.insert(dtn);
            showDienThoai();
            Matxt.setText("");
            HDHtxt.setText("");
            Tentxt.setText("");
            Mautxt.setText("");
            SoLuongtxt.setText("");
        }
    }//GEN-LAST:event_NhapbtnActionPerformed

    private void KhotblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhotblMouseClicked
        // TODO add your handling code here:
        if(selectedP >= 0) {
            DienThoai dtc = DienThoailist.get(selectedP);
            Matxt.setText(dtc.getMaDT());
            Tentxt.setText(dtc.getTenDT());
            HDHtxt.setText(dtc.getHDH());
            SoLuongtxt.setText(Integer.toString(dtc.getSoLuong()));
            Mautxt.setText(dtc.getMauDT());
            Ngaytxt.setDate(dtc.getNgaynhap());
        }
    }//GEN-LAST:event_KhotblMouseClicked
    public final void showDienThoai(){
        tableModel.setRowCount(0);
        DienThoailist = DienThoaimodify.findAll();
        DienThoailist.forEach(dienthoai -> {
            tableModel.addRow(new Object[]{dienthoai.getMaDT(), dienthoai.getTenDT(), dienthoai.getHDH(), dienthoai.getMauDT(), dienthoai.getSoLuong(), dienthoai.getNgaynhap()} );
        });
    }
    
    public void NhapPhieu(Phieu a){
        PreparedStatement statement = null;
        Connection conn = null;
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dienthoai","root", "");
            String sql = "INSERT INTO phieunhap (MaDT, TenDT, HDH, MauDT, SoLuong, Ngay) values (?, ?, ?, ?, ?, ?)";
            statement = conn.prepareCall(sql);
             statement.setString(1, a.getMaDT());
             statement.setString(2, a.getTenDT());
             statement.setString(3, a.getHDH());
             statement.setString(4, a.getMauDT());
             statement.setInt(5,a.getSoluong());
             statement.setDate(6, new java.sql.Date(a.getNgay().getTime()));
             statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HDHtxt;
    private javax.swing.JTable Khotbl;
    private javax.swing.JTextField Matxt;
    private javax.swing.JTextField Mautxt;
    private com.toedter.calendar.JDateChooser Ngaytxt;
    private javax.swing.JButton Nhapbtn;
    private javax.swing.JTextField SoLuongtxt;
    private javax.swing.JTextField Tentxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
