/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhodt;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kax20
 */
public class QuanLyKho extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    List<DienThoai> DienThoailist = new ArrayList<>();
    int selectedP = -1;
    /**
     * Creates new form QuanLyKho
     */
    public QuanLyKho() {
        initComponents();
        tableModel = (DefaultTableModel) Khotbl.getModel();
        DienThoailist = DienThoaimodify.findAll();
        showDienThoai();
        Khotbl.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                selectedP = Khotbl.getSelectedRow();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }
    public final void showDienThoai(){
        tableModel.setRowCount(0);
        DienThoailist.forEach((DienThoai dienthoai) -> {
            tableModel.addRow(new Object[]{dienthoai.getMaDT(), dienthoai.getTenDT(), dienthoai.getHDH(), dienthoai.getMauDT(), dienthoai.getSoLuong(), dienthoai.getNgaynhap()} );
        });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Matxt = new javax.swing.JTextField();
        Tentxt = new javax.swing.JTextField();
        SoLuongtxt = new javax.swing.JTextField();
        Mautxt = new javax.swing.JTextField();
        HDHtxt = new javax.swing.JTextField();
        Ngaytxt = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Khotbl = new javax.swing.JTable();
        Thembtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Suabtn = new javax.swing.JButton();
        Sortcbb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Điện Thoại");

        jLabel2.setText("Tên Điện Thoại");

        jLabel3.setText("Màu ");

        jLabel4.setText("Hệ Điều Hành");

        jLabel5.setText("Số Lượng");

        jLabel6.setText("Ngày");

        Khotbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Điện Thoại", "Tên Điện Thoại", "Hệ Điều Hành", "Màu ", "Số Lượng", "Ngày"
            }
        ));
        Khotbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhotblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Khotbl);

        Thembtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/Science-Plus2-Math-icon.png"))); // NOI18N
        Thembtn.setText("Thêm");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });

        Xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/delete-icon.png"))); // NOI18N
        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });

        Suabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/fix-it-icon.png"))); // NOI18N
        Suabtn.setText("Sửa");
        Suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuabtnActionPerformed(evt);
            }
        });

        Sortcbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp theo mã", "Sắp xếp theo tên" }));
        Sortcbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortcbbActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/sort-descending-icon.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setText("QUẢN LÝ KHO");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/options-2-icon.png"))); // NOI18N
        jMenu3.setText("Option");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/back-icon.png"))); // NOI18N
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/Users-Name-icon_1.png"))); // NOI18N
        jMenuItem2.setText("SignOut");
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Sortcbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tentxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Matxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HDHtxt, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SoLuongtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Mautxt)
                                    .addComponent(Ngaytxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Thembtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(Xoabtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(Suabtn)
                                        .addGap(0, 21, Short.MAX_VALUE)))))
                        .addGap(376, 376, 376))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Matxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(HDHtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Mautxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SoLuongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Ngaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sortcbb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thembtn)
                    .addComponent(Xoabtn)
                    .addComponent(Suabtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        // TODO add your handling code here:
        String ma = Matxt.getText();
        String ten = Tentxt.getText();
        String hdh = HDHtxt.getText();
        int soluong = Integer.parseInt(SoLuongtxt.getText());
        String mau = Mautxt.getText();
        Date ngay = Ngaytxt.getDate();
        DienThoai dtn = new DienThoai(ma, ten, hdh, mau, soluong, ngay);
        DienThoaimodify.insert(dtn);
        DienThoailist = DienThoaimodify.findAll();
        showDienThoai();
    }//GEN-LAST:event_ThembtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        // TODO add your handling code here:
        if(selectedP >= 0) {
            DienThoai dtc = DienThoailist.get(selectedP);
            DienThoaimodify.delete(dtc.getMaDT());
            DienThoailist = DienThoaimodify.findAll();
            showDienThoai();
        }
    }//GEN-LAST:event_XoabtnActionPerformed

    private void KhotblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhotblMouseClicked
        // TODO add your handling code here:
        if(selectedP >= 0) {
            DienThoai dtc = DienThoailist.get(selectedP);
            Matxt.setText(dtc.getMaDT());
            Tentxt.setText(dtc.getTenDT());
            HDHtxt.setText(dtc.getHDH());
            SoLuongtxt.setText(Integer.toString(dtc.getSoLuong()));
            Mautxt.setText(dtc.getMauDT());
            Ngaytxt.setDate(dtc.getNgaynhap());
        }
    }//GEN-LAST:event_KhotblMouseClicked

    private void SuabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuabtnActionPerformed
        // TODO add your handling code here:
        String ma = Matxt.getText();
        String ten = Tentxt.getText();
        String hdh = HDHtxt.getText();
        int soluong = Integer.parseInt(SoLuongtxt.getText());
        String mau = Mautxt.getText();
        Date ngay = Ngaytxt.getDate();
        DienThoai dtn = new DienThoai(ma, ten, hdh, mau, soluong, ngay);
        DienThoaimodify.update(dtn);
        DienThoailist = DienThoaimodify.findAll();
        showDienThoai();
    }//GEN-LAST:event_SuabtnActionPerformed

    private void SortcbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortcbbActionPerformed
        // TODO add your handling code here:
        if(Sortcbb.getSelectedItem().equals("Sắp xếp theo mã")){
            Collections.sort(DienThoailist, (DienThoai o1, DienThoai o2) -> o1.getMaDT().compareTo(o2.getMaDT()));
            showDienThoai();
        }
        if(Sortcbb.getSelectedItem().equals("Sắp xếp theo tên")){
            Collections.sort(DienThoailist, (DienThoai o1, DienThoai o2) -> o1.getTenDT().compareTo(o2.getTenDT()));
            showDienThoai();
        }
    }//GEN-LAST:event_SortcbbActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu a = new Menu();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLyKho().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HDHtxt;
    private javax.swing.JTable Khotbl;
    private javax.swing.JTextField Matxt;
    private javax.swing.JTextField Mautxt;
    private com.toedter.calendar.JDateChooser Ngaytxt;
    private javax.swing.JTextField SoLuongtxt;
    private javax.swing.JComboBox<String> Sortcbb;
    private javax.swing.JButton Suabtn;
    private javax.swing.JTextField Tentxt;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
