/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhodt;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kax20
 */
public class XuatKho extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<DienThoai> DienThoailist = new ArrayList<>();
    int selectedP = -1;
    /**
     * Creates new form XuatKho
     */
    public XuatKho() {
        initComponents();
        tableModel = (DefaultTableModel) Khotbl.getModel();
        showDienThoai();
        Khotbl.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                selectedP = Khotbl.getSelectedRow();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Khotbl = new javax.swing.JTable();
        Xuatbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Khotbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Điện Thoại", "Tên Điện Thoại", "Hệ Điều Hành", "Màu ", "Số Lượng", "Ngày"
            }
        ));
        Khotbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhotblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Khotbl);

        Xuatbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhodt/Data-Export-icon.png"))); // NOI18N
        Xuatbtn.setText("Xuất");
        Xuatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Xuatbtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Xuatbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void showDienThoai(){
        tableModel.setRowCount(0);
        DienThoailist = DienThoaimodify.findAll();
        DienThoailist.forEach(dienthoai -> {
            tableModel.addRow(new Object[]{dienthoai.getMaDT(), dienthoai.getTenDT(), dienthoai.getHDH(), dienthoai.getMauDT(), dienthoai.getSoLuong(), dienthoai.getNgaynhap()} );
        });
    }
    private void KhotblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhotblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KhotblMouseClicked

    private void XuatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatbtnActionPerformed
        // TODO add your handling code here:
            DienThoai dtc = DienThoailist.get(selectedP);
            int xuat = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Nhập số lượng xuất"));
            if(xuat > dtc.getSoLuong()){
                JOptionPane.showMessageDialog(rootPane, "Số lượng xuất vượt quá số lượng tồn kho");
            }
            else{
                Phieu a = new Phieu(dtc.getMaDT(), dtc.getTenDT(), dtc.getHDH(), dtc.getMauDT(), xuat, dtc.getNgaynhap());
                dtc.setSoLuong(dtc.getSoLuong() - xuat);
                DienThoaimodify.update(dtc);
                XuatPhieu(a);
                showDienThoai();
            }
    }//GEN-LAST:event_XuatbtnActionPerformed

    public void XuatPhieu(Phieu a){
        long millis=System.currentTimeMillis();   
        java.sql.Date date=new java.sql.Date(millis);  
        PreparedStatement statement = null;
        Connection conn = null;
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dienthoai","root", "");
            String sql = "INSERT INTO phieuxuat (MaDT, TenDT, HDH, MauDT, SoLuong, Ngay) values (?, ?, ?, ?, ?, ?)";
            statement = conn.prepareCall(sql);
             statement.setString(1, a.getMaDT());
             statement.setString(2, a.getTenDT());
             statement.setString(3, a.getHDH());
             statement.setString(4, a.getMauDT());
             statement.setInt(5,a.getSoluong());
            statement.setDate(6, date);
             statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Khotbl;
    private javax.swing.JButton Xuatbtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
